### ISSUE TITLE
Issue: Selenium cannot find form search box.

### ISSUE THREAD

**Issue by jlt5389** [jlt5389/selenium_scraper#1]
Traceback (most recent call last):
  File "C:\Users\James Fung\Git\repositories\selenium_scraper\scraper_main.py", line 41, in <module>
    reports_Management_formsreport_forms_element = element(reports_Management_formsreport_forms_Xpath)
  File "C:\Users\James Fung\Git\repositories\selenium_scraper\test_functions.py", line 12, in element
    return WebDriverWait(driver, 10).until(lambda driver: driver.find_element_by_xpath(xpath))
  File "C:\Python3\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: #

**Comment by jlt5389** [comment]
Issue solved. .click() xpath of dropdown item.
